# Generated by Django 4.2.7 on 2023-12-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_tfidf_similarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfidf_similarity',
            old_name='similarity',
            new_name='tfidf',
        ),
        migrations.AlterModelTable(
            name='tfidf_similarity',
            table='tf-idf',
        ),
    ]
