# Generated by Django 4.2.7 on 2023-12-04 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_rename_similarity_tfidf_similarity_tfidf_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TFIDF_Similarity',
        ),
    ]
