# Generated by Django 4.2.7 on 2023-12-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_name_alter_user_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
