#version: '3'
#
#services:
#  db:
#    image: postgres
#    expose:
#      -  "5432"
#    networks:
#      - djangonetwork
#    env_file: ./RecSystem/.env
#  web:
#    restart: always
#    build: .
#    command: python manage.py runserver 0.0.0.0:8010
#    volumes:
#      - .:/RecSys
#    ports:
#      - "8000:8000"
#    env_file:
#      - ./RecSystem/.env
#    networks:
#      - djangonetwork
#    links:
#      - db:db
#    depends_on:
#      - db
#
#
#
#
#networks:
#    djangonetwork:
#      driver: bridge
#

version: '3'

services:
  # Сервис для PostgreSQL
  db:
    image: postgres:latest
    env_file: ./RecSystem/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  # Сервис для Django
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/RecSys
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    links:
      - db:db
    depends_on:
      - db

networks:
  mynetwork:  # Название сети, используемое выше
    driver: bridge  # Можете выбрать другой драйвер, если это необходимо


volumes:
  postgres_data:
