# Generated by Django 4.2.7 on 2023-11-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('TV', 'Tv'), ('OVA', 'Ova'), ('Movie', 'Movie'), ('Special', 'Special'), ('ONA', 'Ona')], max_length=8)),
                ('episodes', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('members', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(default=-1)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApi.anime')),
            ],
        ),
    ]
