# Generated by Django 4.2.7 on 2023-11-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='user_id',
        ),
    ]
