# Generated by Django 4.2.7 on 2023-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0003_remove_anime_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
