# Generated by Django 4.2.7 on 2023-11-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0007_watchedlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='id',
        ),
        migrations.AlterField(
            model_name='anime',
            name='anime_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
