# Generated by Django 4.2.7 on 2023-11-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0008_remove_anime_id_alter_anime_anime_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrating',
            constraint=models.UniqueConstraint(fields=('user_id', 'anime_id'), name='user_anime_rating'),
        ),
    ]
