# Generated by Django 4.2.7 on 2023-11-19 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productApi', '0008_remove_anime_id_alter_anime_anime_id'),
        ('collector', '0003_alter_conversion_content_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversion',
            new_name='Logs',
        ),
    ]
